from __future__ import annotations

from pantry_backend.utils.date_time_styling import (
    DISPLAY_DATE_FORMAT,
    ISO_DATE_FORMAT,
    ISO_DATETIME_FORMAT,
    ISO_DATETIME_WITH_TZ_FORMAT,
    SHORT_DATE_FORMAT,
    TIME_24H_FORMAT,
    TIME_FORMAT,
    VERBOSE_DATE_FORMAT,
    ensure_timezone_aware,
    format_datetime_display,
    format_days_until,
    format_display_date,
    format_iso_date,
    format_iso_datetime,
    format_relative_time,
    format_time,
)
from pantry_backend.utils.constants import (
    DEFAULT_PERSONAL_HOUSEHOLD_NAME,
    EMBEDDING_QUEUE_MAIN,
    EMBEDDINGS_TABLE_NAME,
    INVITE_CODE_LENGTH,
    ITEMS_TABLE_NAME,
    MAX_PAGE_SIZE,
    MAX_INVITE_CODE_RETRIES,
    PANTRY_HOUSEHOLD_CACHE_TTL_SECONDS,
    PANTRY_USER_CACHE_TTL_SECONDS,
    POSTGRES_UNIQUE_VIOLATION_CODE,
)
from pantry_backend.utils.embedding import embeddings_client
from pantry_backend.utils.formatters import to_public_dict, wrap_response
from pantry_backend.utils.validators import (
    ValidationResult,
    normalize_title_case,
    normalize_trim,
    validate_in_set,
)

__all__ = [
    "embeddings_client",
    "to_public_dict",
    "wrap_response",
    "ValidationResult",
    "normalize_title_case",
    "normalize_trim",
    "validate_in_set",
    "format_iso_date",
    "format_iso_datetime",
    "format_display_date",
    "format_time",
    "format_relative_time",
    "format_days_until",
    "format_datetime_display",
    "ensure_timezone_aware",
    "ISO_DATE_FORMAT",
    "ISO_DATETIME_FORMAT",
    "ISO_DATETIME_WITH_TZ_FORMAT",
    "DISPLAY_DATE_FORMAT",
    "SHORT_DATE_FORMAT",
    "VERBOSE_DATE_FORMAT",
    "TIME_FORMAT",
    "TIME_24H_FORMAT",

    "DEFAULT_PERSONAL_HOUSEHOLD_NAME",
    "ITEMS_TABLE_NAME",
    "EMBEDDINGS_TABLE_NAME",
    "EMBEDDING_QUEUE_MAIN",
    "INVITE_CODE_LENGTH",
    "MAX_PAGE_SIZE",
    "MAX_INVITE_CODE_RETRIES",
    "POSTGRES_UNIQUE_VIOLATION_CODE",
    "PANTRY_HOUSEHOLD_CACHE_TTL_SECONDS",
    "PANTRY_USER_CACHE_TTL_SECONDS",
]
